import {Roboto, Playwrite_AU_SA, Playfair_Display, Oswald} from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const playfairDisplay = Playfair_Display({
  variable: "--font-playfairDisplay-sans",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald-sans",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],
});

const playwriteAustraliaSa = Playwrite_AU_SA({
  variable: "--font-playwriteAustraliaSa-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Faizan Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={``}>
      <body
        className={`${roboto.className}  relative min-h-screen`}
      >
        <div className="bg-linear-to-bl from-gray-300 to-white-200 inset-x-0 absolute left-0 top-0 " >
        
       <Navbar /> 
        {children}
        
        </div>
      </body>
    </html>
  );
}
